### ISSUE TITLE
STANFORD NER

### ISSUE THREAD

**Issue by li10141110** [may-/cnn-re-tf#4]
hello!
(base_path = "http://en.wikipedia.org/w/api.php?format=xml&action=query"
    query = base_path + "&list=random&rnnamespace=0&rnlimit=%d" % limit)
what is mean????
I can not get useful infomation from this url.

**Comment by may-** [comment]
Hi,

There, I call RESTful MediaWiki API [https://en.wikipedia.org/w/api.php](https://en.wikipedia.org/w/api.php) with following options:

- format = xml
- action = query
- list = random
- rnnamespace = 0    (built-in namespace numbers: you can check [here](https://www.mediawiki.org/wiki/Manual:Namespace#Built-in_namespaces).)
- rnlimit = 10    (this number is specified by the variable `limit` in my code.)

So, the URL looks like:
<span style="white-space:nowrap">http://en.wikipedia.org/w/api.php?format=xml&action=query&list=random&rnnamespace=0&rnlimit=10</span>

In this query, You'll get 10 random wikipedia article IDs (normal articles only, no category page or anything others) in xml format.


You can test the API options in [sandbox](https://en.wikipedia.org/wiki/Special:ApiSandbox#action=query&format=xml&list=random&rnnamespace=0&rnlimit=10).


Did I answer your question?

**Comment by li10141110** [comment]
yes,very thank you!you answer my question perfectly!But I have another question,I can not run that program successfully.It will be wrong,and it shows that: 
Traceback (most recent call last):
  File "/home/wuyujuan/Desktop/cnn-re-tf-master1/distant_supervision.py", line 693, in <module>
    main()
  File "/home/wuyujuan/Desktop/cnn-re-tf-master1/distant_supervision.py", line 682, in main
    extract_positive()
  File "/home/wuyujuan/Desktop/cnn-re-tf-master1/distant_supervision.py", line 570, in extract_positive
    entities = util.load_from_dump(os.path.join(data_dir, "entities.cPickle"))
  File "/home/wuyujuan/Desktop/cnn-re-tf-master1/util.py", line 285, in load_from_dump
    with open(filename, 'rb') as infile:
IOError: [Errno 2] No such file or directory: '/home/wuyujuan/Desktop/cnn-re-tf-master1/data/entities.cPickle'
Can you help me solve this problem?very thank you!

**Comment by may-** [comment]
Ah, this is a known problem. I'll fix it in future, but for now, could you please try [this](https://github.com/may-/cnn-re-tf/issues/3#issuecomment-309293662)? Sorry for inconvenience.

If you still get any error, please let me know :)

**Comment by li10141110** [comment]
dear,
I'm sorry but I have tried this before and it does't work.
following are my results:
/home/wuyujuan/Envs/cnn_re/bin/python /home/wuyujuan/Desktop/cnn-re-tf-another_try/distant_supervision.py
===== step 1 =====
[1/4] Downloading wiki articles ...
Traceback (most recent call last):

  File "/home/wuyujuan/Desktop/cnn-re-tf-another_try/distant_supervision.py", line 694, in <module>
    main()
  File "/home/wuyujuan/Desktop/cnn-re-tf-another_try/distant_supervision.py", line 682, in main
    positive_examples()
  File "/home/wuyujuan/Desktop/cnn-re-tf-another_try/distant_supervision.py", line 453, in positive_examples
    ret = loop(step, doc_id, limit, entities, relations, counter)
  File "/home/wuyujuan/Desktop/cnn-re-tf-another_try/distant_supervision.py", line 344, in loop
    docs = download_wiki_articles(doc_id, limit)
  File "/home/wuyujuan/Desktop/cnn-re-tf-another_try/distant_supervision.py", line 73, in download_wiki_articles
    pages = bs(r, "html.parser").findAll('page')
  File "/home/wuyujuan/Envs/cnn_re/lib/python2.7/site-packages/bs4/__init__.py", line 192, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()

Process finished with exit code 1

thank for your time,may!

**Comment by li10141110** [comment]
following are my virtualenv
centos7.3
python2.7
backports-abc (0.5)
beautifulsoup4 (4.6.0)
certifi (2017.4.17)
chardet (3.0.4)
cycler (0.10.0)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
idna (2.5)
matplotlib (2.0.2)
mock (2.0.0)
nose (1.3.7)
numpy (1.11.1)
olefile (0.44)
pandas (0.20.2)
pbr (3.1.1)
Pillow (4.1.1)
pip (9.0.1)
protobuf (3.3.0)
pyparsing (2.2.0)
python-dateutil (2.6.0)
pytz (2017.2)
requests (2.18.1)
scikit-learn (0.18.2)
scipy (0.19.0)
setuptools (36.2.0)
singledispatch (3.4.0.3)
six (1.10.0)
subprocess32 (3.2.7)
tensorflow-gpu (1.0.0)
tornado (4.5.1)
urllib3 (1.21.1)
Werkzeug (0.12.2)
wheel (0.29.0)

**Comment by li10141110** [comment]
I changed my env from centos to win7 and now it seems that something wrong happened

===== step 1 =====
[1/4] Downloading wiki articles ...
[2/4] Performing named entity recognition ...
Error: Could not find or load main class edu.stanford.nlp.ie.crf.CRFClassifier
Error: Could not find or load main class edu.stanford.nlp.ie.crf.CRFClassifier
Error: Could not find or load main class edu.stanford.nlp.ie.crf.CRFClassifier
Traceback (most recent call last):
  File "C:/Users/Jason Lee/Desktop/cnn-re-tf-master/distant_supervision.py", line 700, in <module>
    main()
  File "C:/Users/Jason Lee/Desktop/cnn-re-tf-master/distant_supervision.py", line 688, in main
    positive_examples()
  File "C:/Users/Jason Lee/Desktop/cnn-re-tf-master/distant_supervision.py", line 459, in positive_examples
    ret = loop(step, doc_id, limit, entities, relations, counter)
  File "C:/Users/Jason Lee/Desktop/cnn-re-tf-master/distant_supervision.py", line 360, in loop
    doc_id.extend([int(s) for s in wiki_data.doc_id.unique()])
  File "I:\anaconda2\Ancona\lib\site-packages\pandas\core\generic.py", line 2744, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'doc_id'

thank for your time,may!

**Comment by li10141110** [comment]
dear,
I got the following after several days' work:
[1/4] Downloading wiki articles ...
['16648-.txt' '17514-.txt' '24591-.txt' '28182-.txt' '28356-.txt'
 '28852-.txt' '36847-.txt' '36896-.txt' '7252-.txt']
[2/4] Performing named entity recognition ...
Invoked on Fri Jul 21 21:28:36 CST 2017 with arguments: -loadClassifier C:/Users/Jason Lee/Desktop/cnn-re-tf-master/stanford-ner-jason\classifiers\english.all.3class.distsim.crf.ser.gz -outputFormat tabbedEntities -textFile C:/Users/Jason Lee/Desktop/cnn-re-tf-master\data\orig\7252-.txt
loadClassifier=C:/Users/Jason Lee/Desktop/cnn-re-tf-master/stanford-ner-jason\classifiers\english.all.3class.distsim.crf.ser.gz
textFile=C:/Users/Jason Lee/Desktop/cnn-re-tf-master\data\orig\7252-.txt
outputFormat=tabbedEntities
Loading classifier from C:/Users/Jason Lee/Desktop/cnn-re-tf-master/stanford-ner-jason\classifiers\english.all.3class.distsim.crf.ser.gz ... done [3.9 sec].
CRFClassifier tagged 4376 words in 177 documents at 4635.59 words per second.
[3/4] Linking entities ...
[4/4] Linking predicates ...
Traceback (most recent call last):
  File "C:/Users/Jason Lee/Desktop/cnn-re-tf-master/distant_supervision.py", line 718, in <module>
    main()
  File "C:/Users/Jason Lee/Desktop/cnn-re-tf-master/distant_supervision.py", line 706, in main
    positive_examples()
  File "C:/Users/Jason Lee/Desktop/cnn-re-tf-master/distant_supervision.py", line 477, in positive_examples
    ret = loop(step, doc_id, limit, entities, relations, counter)
  File "C:/Users/Jason Lee/Desktop/cnn-re-tf-master/distant_supervision.py", line 406, in loop
    relations[(subj, obj)] = search_property(arg1, arg2)
  File "C:/Users/Jason Lee/Desktop/cnn-re-tf-master/distant_supervision.py", line 299, in search_property
    response = r.json()
AttributeError: 'NoneType' object has no attribute 'json'

It seems that I have problem in the fourth step.It would be helpful if you can provide me with some suggestions.
Thank you for your time!

**Comment by li10141110** [comment]
dear, 
everything is ok，thank you for your attention! I have got my own articles.
best wishes!

**Comment by may-** [comment]
Sorry, I had no time to look at your problem. But you found a solution...
